// ============================================================
//  impressao_qztray.js
//  Copie este arquivo para: src/utils/impressao_qztray.js
//
//  Dependência:
//    <script src="https://cdn.qz.io/2.2.4/qz-tray.js"></script>
//    (adicione no seu index.html, ou instale via npm: npm install qz-tray)
// ============================================================

// ── Logo já convertido para ESC/P (gerado automaticamente) ──────────────────
const LOGO_ESCP_BASE64 = "GzMYGyoEvgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQobKgS+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANChsqBL4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0KGyoEvgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQobKgS+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANChsqBL4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0KGyoEvgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQMDAwcHBwYOBg4ODA4ODA4ODA4OBg4HBgcHAwMDAQEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQobKgS+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQMDBw4eHDh4cODgwMCAgIAAAAAAAAAAAAAAAAEBAQEAAAAAAAAAAAAAgICAwMDg4HBwODwcDg8HAwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANChsqBL4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADBx8eePDgwIABAQMDAwMDBwMHBwYPBw8PDx8OHDw4cODgwMDAwOBgcHA4OBwcDg4HBwMDAQEAAAAAAAAAAADAwPB4PB4PBwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0KGyoEvgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBx9++OCAAAAAADx8/ufDg4OHB44fPz1wcODAgYMHDx4cOHDg4MEDAw8OPDgQAAAAAQMDAAAAgIDAwODgcHA4ODx8fn43PzscHIzO9v8/DwMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQobKgS+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADP//0gQEBAwEDAwMHBwc//vDAgAAAAP//VQAAAAH//6QAAAAACz//4MCAAAADDx88ePDggAABAQEBAQMBAwMDAwMDAAAAAAD//0gAAAAAAADg/P8fAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANChsqBL4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACv//4MDAwIDAgICBBz/+8IAAAAAAAAAA/P5fBwMBX//0AAAAAB//+gAAAAADP//wAAAAAQcf/vDg4Pj8n4eDgACAAAAAAQMDT/7+AAAAAAAAAAAA+v9/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0KGyoEvgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQ//8XAAAAAAAPP//xgQAAAAAADB0PDwcHAwEBgMDg4PA4PBy+/+8HDw4cPPj4eDBwcGDg8P4/BwEBAQEBwfn/Pzlw4ODAgIAAAAAAAAAAAAAAAAHf//oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQobKgS+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8P4/BwEAAAAAgMDg4HBwOBweXv//AACAwMDg/386ODxw8ODAgAAAAAAAAAAAAAAHDz548ODAwICAgIDAgMDg4HA8Hw8HBwMDAQEAAAAAAAMff/jgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANChsqBL4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDw+D4fBwEBAQEDAwcHBg7f//8AAAAAAAD//6oAAAAAAAAAAAAAAAAAAAAAKf//gAAAAAABAAAAAAAAAAAAAACr/38AgIDAwOHjd3988OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0KGyoEvgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA4PD4vI6PAwMBAFv//wAAAAAAAP//qgAAAAAAAAAAAAAAAAAAAAAAwODweDhw4ODgeDg4cODg8Dg4cODDAwcPHjx48OCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQobKgS+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAwODgcPj4HBwODgcH//+rAQEBAQAAAAAAAAAAAAAAAAAAAAEBAQEDAwMHBw4OHBw4OHDw4MDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANChsqBL4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgICAwMDAwODA4ODgwODgwODgwODAwMDAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0KGyoEvgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQobKgS+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANChsqBL4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0KGyoEvgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQobKgS+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANChsqBL4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0KGzI=";

// ── Nome da impressora no Windows (ajuste se necessário) ────────────────────
const NOME_IMPRESSORA = "EPSON FX-890";

// ── Conecta ao QZ Tray (chame uma vez ao iniciar o app) ─────────────────────
export async function conectar() {
  if (qz.websocket.isActive()) return;
  await qz.websocket.connect();
}

// ── Desconecta (opcional, ao fechar o app) ───────────────────────────────────
export async function desconectar() {
  if (qz.websocket.isActive()) {
    await qz.websocket.disconnect();
  }
}

// ── Função principal de impressão ────────────────────────────────────────────
/**
 * Imprime um relatório na matricial via QZ Tray.
 *
 * @param {object}   params
 * @param {string}   params.cabecalho     - Título em negrito (ex: "RELATÓRIO 05/2026")
 * @param {string[]} params.linhas        - Linhas do corpo do relatório
 * @param {boolean}  [params.comLogo]     - Imprimir logo? (padrão: true)
 * @param {boolean}  [params.avancarPagina] - Form feed no final? (padrão: true)
 */
export async function imprimirRelatorio({
  cabecalho,
  linhas = [],
  comLogo = true,
  avancarPagina = true,
}) {
  await conectar();

  const config = qz.configs.create(NOME_IMPRESSORA);

  const dados = [];

  // Reset da impressora
  dados.push({ type: "raw", format: "plain", data: "\x1b@" });

  // Logo
  if (comLogo) {
    dados.push({ type: "raw", format: "base64", data: LOGO_ESCP_BASE64 });
    dados.push({ type: "raw", format: "plain", data: "\n" });
  }

  // Cabeçalho em negrito
  if (cabecalho) {
    dados.push({ type: "raw", format: "plain", data: "\x1bE" });   // negrito ON
    dados.push({ type: "raw", format: "plain", data: cabecalho + "\r\n" });
    dados.push({ type: "raw", format: "plain", data: "\x1bF" });   // negrito OFF
  }

  // Linhas do corpo
  for (const linha of linhas) {
    dados.push({ type: "raw", format: "plain", data: linha + "\r\n" });
  }

  // Form feed (avança o papel)
  if (avancarPagina) {
    dados.push({ type: "raw", format: "plain", data: "\x0c" });
  }

  await qz.print(config, dados);
}


// ============================================================
//  EXEMPLO DE USO no seu componente React:
//
//  import { imprimirRelatorio } from "../utils/impressao_qztray";
//
//  async function handleImprimir() {
//    try {
//      await imprimirRelatorio({
//        cabecalho: `RELATÓRIO DE VENDAS - ${dataAtual}`,
//        linhas: [
//          "----------------------------------------",
//          `Cliente : ${cliente.nome}`,
//          `Pedido  : ${pedido.numero}`,
//          `Valor   : R$ ${pedido.valor}`,
//          "----------------------------------------",
//        ],
//        comLogo: true,
//        avancarPagina: true,
//      });
//      alert("Impresso com sucesso!");
//    } catch (erro) {
//      alert("Erro ao imprimir: " + erro.message);
//    }
//  }
//
//  <button onClick={handleImprimir}>Imprimir</button>
// ============================================================
