-- Script para criar a tabela de notas no Supabase
CREATE TABLE IF NOT EXISTS public.notas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_email VARCHAR(255) NOT NULL,
    data DATE NOT NULL,
    conteudo TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT uk_usuario_data UNIQUE (usuario_email, data)
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.notas ENABLE ROW LEVEL SECURITY;

-- Política de acesso permissivo para leitura e escrita na tabela notas
DROP POLICY IF EXISTS "Autenticados: acesso total notas" ON public.notas;
CREATE POLICY "Autenticados: acesso total notas" ON public.notas FOR ALL TO public USING (true) WITH CHECK (true);
